language: cpp
sudo: required
dist: bionic
addons:
  apt:
    packages:
    - qtbase5-dev
    - qtbase5-dev-tools
    - qt5-default
    - qtdeclarative5-dev
    - qtdeclarative5-private-dev
    - qml-module-qtquick-controls
    - qml-module-qtquick-controls2
    - qtbase5-private-dev
    - cmake
before_install:
  - git clone https://code.qt.io/qt/qtftp.git/
  - cd qtftp
  - qmake
  - make
  - sudo make install
  - cd ..
  - sudo rm -r -f qtftp
  - git clone --recursive https://codereview.qt-project.org/qt-labs/qthttpserver
  - cd qthttpserver
  - qmake
  - make
  - sudo make install
  - cd ..
  - sudo rm -r -f qthttpserver
compiler: g++
script:
  - qmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ls lib
  - ls bin
  - cp -r lib bin/plugins
  - make test
