language: cpp
sudo: required
dist: trusty
before_install:
  - sudo apt-get install g++-7
  - export CC=gcc-7
  - export CXX=g++-7
  - sudo apt-get update
  - sudo apt-get install qt5-default 
  - sudo apt-get install qttools5-dev-tools 
  - sudo apt-get install cmake
compiler: g++
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - make test
