language: cpp
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-9 g++-9
  - export CC=gcc-9
  - export CXX=g++-9
  - sudo apt-get install cmake
  - sudo apt-get install qt510-meta-full
  - source /opt/qt510/bin/qt510-env.sh
compiler: g++
script:
  - qmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ls lib
  - ls bin
  - cp lib bin/plugins
  - make test
