#ifndef APPLICATIONSERVERCORE_GLOBAL_H
#define APPLICATIONSERVERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(APPLICATIONSERVERCORE_LIBRARY)
#  define APPLICATIONSERVERCORE_EXPORT Q_DECL_EXPORT
#else
#  define APPLICATIONSERVERCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // APPLICATIONSERVERCORE_GLOBAL_H
